/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package uk.co.dave.shared.fxrateevent;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FxRate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2273904616364115651L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FxRate\",\"namespace\":\"uk.co.dave.shared.fxrateevent\",\"fields\":[{\"name\":\"from\",\"type\":\"string\"},{\"name\":\"to\",\"type\":\"string\"},{\"name\":\"rate\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":7,\"scale\":6}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FxRate> ENCODER =
      new BinaryMessageEncoder<FxRate>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FxRate> DECODER =
      new BinaryMessageDecoder<FxRate>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FxRate> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FxRate> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FxRate> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FxRate>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FxRate to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FxRate from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FxRate instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FxRate fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence from;
  @Deprecated public java.lang.CharSequence to;
  @Deprecated public java.nio.ByteBuffer rate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FxRate() {}

  /**
   * All-args constructor.
   * @param from The new value for from
   * @param to The new value for to
   * @param rate The new value for rate
   */
  public FxRate(java.lang.CharSequence from, java.lang.CharSequence to, java.nio.ByteBuffer rate) {
    this.from = from;
    this.to = to;
    this.rate = rate;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return from;
    case 1: return to;
    case 2: return rate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: from = (java.lang.CharSequence)value$; break;
    case 1: to = (java.lang.CharSequence)value$; break;
    case 2: rate = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'from' field.
   * @return The value of the 'from' field.
   */
  public java.lang.CharSequence getFrom() {
    return from;
  }


  /**
   * Sets the value of the 'from' field.
   * @param value the value to set.
   */
  public void setFrom(java.lang.CharSequence value) {
    this.from = value;
  }

  /**
   * Gets the value of the 'to' field.
   * @return The value of the 'to' field.
   */
  public java.lang.CharSequence getTo() {
    return to;
  }


  /**
   * Sets the value of the 'to' field.
   * @param value the value to set.
   */
  public void setTo(java.lang.CharSequence value) {
    this.to = value;
  }

  /**
   * Gets the value of the 'rate' field.
   * @return The value of the 'rate' field.
   */
  public java.nio.ByteBuffer getRate() {
    return rate;
  }


  /**
   * Sets the value of the 'rate' field.
   * @param value the value to set.
   */
  public void setRate(java.nio.ByteBuffer value) {
    this.rate = value;
  }

  /**
   * Creates a new FxRate RecordBuilder.
   * @return A new FxRate RecordBuilder
   */
  public static uk.co.dave.shared.fxrateevent.FxRate.Builder newBuilder() {
    return new uk.co.dave.shared.fxrateevent.FxRate.Builder();
  }

  /**
   * Creates a new FxRate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FxRate RecordBuilder
   */
  public static uk.co.dave.shared.fxrateevent.FxRate.Builder newBuilder(uk.co.dave.shared.fxrateevent.FxRate.Builder other) {
    if (other == null) {
      return new uk.co.dave.shared.fxrateevent.FxRate.Builder();
    } else {
      return new uk.co.dave.shared.fxrateevent.FxRate.Builder(other);
    }
  }

  /**
   * Creates a new FxRate RecordBuilder by copying an existing FxRate instance.
   * @param other The existing instance to copy.
   * @return A new FxRate RecordBuilder
   */
  public static uk.co.dave.shared.fxrateevent.FxRate.Builder newBuilder(uk.co.dave.shared.fxrateevent.FxRate other) {
    if (other == null) {
      return new uk.co.dave.shared.fxrateevent.FxRate.Builder();
    } else {
      return new uk.co.dave.shared.fxrateevent.FxRate.Builder(other);
    }
  }

  /**
   * RecordBuilder for FxRate instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FxRate>
    implements org.apache.avro.data.RecordBuilder<FxRate> {

    private java.lang.CharSequence from;
    private java.lang.CharSequence to;
    private java.nio.ByteBuffer rate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(uk.co.dave.shared.fxrateevent.FxRate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.from)) {
        this.from = data().deepCopy(fields()[0].schema(), other.from);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.to)) {
        this.to = data().deepCopy(fields()[1].schema(), other.to);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.rate)) {
        this.rate = data().deepCopy(fields()[2].schema(), other.rate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing FxRate instance
     * @param other The existing instance to copy.
     */
    private Builder(uk.co.dave.shared.fxrateevent.FxRate other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.from)) {
        this.from = data().deepCopy(fields()[0].schema(), other.from);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.to)) {
        this.to = data().deepCopy(fields()[1].schema(), other.to);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rate)) {
        this.rate = data().deepCopy(fields()[2].schema(), other.rate);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'from' field.
      * @return The value.
      */
    public java.lang.CharSequence getFrom() {
      return from;
    }


    /**
      * Sets the value of the 'from' field.
      * @param value The value of 'from'.
      * @return This builder.
      */
    public uk.co.dave.shared.fxrateevent.FxRate.Builder setFrom(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.from = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'from' field has been set.
      * @return True if the 'from' field has been set, false otherwise.
      */
    public boolean hasFrom() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'from' field.
      * @return This builder.
      */
    public uk.co.dave.shared.fxrateevent.FxRate.Builder clearFrom() {
      from = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'to' field.
      * @return The value.
      */
    public java.lang.CharSequence getTo() {
      return to;
    }


    /**
      * Sets the value of the 'to' field.
      * @param value The value of 'to'.
      * @return This builder.
      */
    public uk.co.dave.shared.fxrateevent.FxRate.Builder setTo(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.to = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'to' field has been set.
      * @return True if the 'to' field has been set, false otherwise.
      */
    public boolean hasTo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'to' field.
      * @return This builder.
      */
    public uk.co.dave.shared.fxrateevent.FxRate.Builder clearTo() {
      to = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'rate' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getRate() {
      return rate;
    }


    /**
      * Sets the value of the 'rate' field.
      * @param value The value of 'rate'.
      * @return This builder.
      */
    public uk.co.dave.shared.fxrateevent.FxRate.Builder setRate(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.rate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'rate' field has been set.
      * @return True if the 'rate' field has been set, false otherwise.
      */
    public boolean hasRate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'rate' field.
      * @return This builder.
      */
    public uk.co.dave.shared.fxrateevent.FxRate.Builder clearRate() {
      rate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FxRate build() {
      try {
        FxRate record = new FxRate();
        record.from = fieldSetFlags()[0] ? this.from : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.to = fieldSetFlags()[1] ? this.to : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.rate = fieldSetFlags()[2] ? this.rate : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FxRate>
    WRITER$ = (org.apache.avro.io.DatumWriter<FxRate>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FxRate>
    READER$ = (org.apache.avro.io.DatumReader<FxRate>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










